typography_spectrum: 0.5539632933214307
color:
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
  brandStrength: 0.9135789759457111
  lightness: 0.8955541886389256
  saturation: 0.08253941452130675
  rhythmicContrast: 0.34865142102353275
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3762960936874151
analytics:
  google: null
  facebook: null
  twitter: null
name: Thaesis
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Inspiration * Strategy * Transition
description: Established in 2006
purpose: []
