layout_spectrum: 0.3620160121936351
typography_spectrum: 0.16572170611470938
color:
  brandColors:
    - '#00585F'
    - '#009393'
    - '#FFFCC4'
    - '#F0EDBB'
    - '#FF3800'
  brandStrength: 0.7780877687036991
  lightness: 0.7589602230582386
  saturation: 0.20712730335071683
  rhythmicContrast: 0.6329378893133253
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Thaesis
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Thaesis
description: Established in 2006
purpose: []
