layout_spectrum: 0.7612620929721743
typography_spectrum: 0.6229286477901042
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.5436570949386805
  lightness: 0.27816045889630914
  saturation: 0.2385359255131334
  rhythmicContrast: 0.6893192520365119
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Thaesis
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Thaesis
description: Established in 2006
purpose: []
