typography_spectrum: 0.15769
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.03670173
  lightness: 0.7428856
  saturation: 0.7511653
  rhythmicContrast: 0.515803
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75706
analytics:
  google: null
  facebook: null
  twitter: null
name: Thaesis
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Thaesis
description: Inspiratie * Strategie * Transitie
purpose: []
