layout_spectrum: 0.3620160121936351
typography_spectrum: 0.28757739812135696
color:
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  brandStrength: 0.9351141974329948
  lightness: 0.010894833132624626
  saturation: 0.6900674537755549
  rhythmicContrast: 0.8474883339367807
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Thaesis
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Thaesis
description: Established in 2006
purpose: []
